# Generated by Django 5.2.4 on 2025-07-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
