# Generated by Django 5.2.4 on 2025-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_tree_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_type',
            name='emit_oxygen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tree_type',
            name='utilize_carbon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
