# Generated by Django 5.2.4 on 2025-07-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tree_type_emit_oxygen_tree_type_utilize_carbon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree_type',
            name='emit_oxygen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tree_type',
            name='utilize_carbon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
